### ISSUE TITLE
フォロー機能のボタンのNoMethodError (undefined method `destroy' for nil:NilClass):のエラーに関して

### ISSUE THREAD

**Issue by nao0725** [nao0725/Teach-Market#157]
【解決したい課題】
フォロー機能のフォローボタンを正常に押せるように改善したい

【現状】（エラー内容）

フォロー／フォロワーの一覧で２列目のUserのフォローボタンを押すと下記のエラーが出ます。

NoMethodError (undefined method `destroy' for nil:NilClass):
  
app/models/user.rb:26:in `unfollow'
app/controllers/public/relationships_controller.rb:21:in `destroy'

該当箇所は下記の通りです

````
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
````

１番先頭のフォロー・フォロワーはボタンを押すことができるのですが、
２番目以降のフォロー解除のボタンを押すとエラーが発生します。

【対策と自分の考え】
・非同期処理を呼び出すボタンの属性がidであるため、先頭のjsしか反応しないのではないか
→　classに変更したが、全員のボタンの表示が変わってしまった。

・下記記事を参考にフォロー機能を実装しました。
https://qiita.com/MOEKASAKAI/items/69ae05554b1562a603ea

unfollowメソッドをuser.rbで定義し、コントローラーで使用している点にエラー原因になるものは見つかりませんでした。

**Comment by nao0725** [comment]
非同期の際に一意になるidを渡していなかった

`````
            <div id = "follow_btn">
              <p><%= render "public/relationships/follow_btn", user: user %></p>
            </div>

`````



````
            <div id = "follow_btn_<%= user.id %>">
              <p><%= render "public/relationships/follow_btn", user: user %></p>
            </div>

````

create.js destroy.jsも同様に追加
